openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: API documentation for the application
paths:
  /:
    post:
      summary: Home
      responses:
        '200':
          description: Welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                mob:
                  type: string
                name:
                  type: string
                courses:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: User created successfully
        '400':
          description: Error in registration
        '500':
          description: Internal server error

  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credentials
        '500':
          description: Internal server error

  /dashboard:
    get:
      summary: Get user dashboard
      responses:
        '200':
          description: Dashboard data
        '404':
          description: User not found
        '500':
          description: Internal server error

  /study:
    get:
      summary: Get study content
      responses:
        '200':
          description: Study content data
        '404':
          description: User not found
        '500':
          description: Internal server error
    post:
      summary: Create a new course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_name:
                  type: string
                course_description:
                  type: string
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
      responses:
        '201':
          description: Course created successfully
        '500':
          description: Internal server error

  /study/course_docs:
    get:
      summary: Get course documents
      responses:
        '200':
          description: Course documents data
        '404':
          description: Course not found
        '500':
          description: Internal server error
    post:
      summary: Upload a new course document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doc_title:
                  type: string
                doc_link:
                  type: string
      responses:
        '201':
          description: Document created successfully
        '500':
          description: Internal server error

  /study/practice:
    get:
      summary: Get practice assignments
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Practice assignments data
        '500':
          description: Internal server error
    post:
      summary: Create a new practice assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assignment_title:
                  type: string
                assignment_description:
                  type: string
                due_date:
                  type: string
                  format: date
      responses:
        '201':
          description: Practice assignment created successfully
        '500':
          description: Internal server error

  /study/graded:
    get:
      summary: Get graded assignments
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Graded assignments data
        '500':
          description: Internal server error
    post:
      summary: Create a new graded assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assignment_title:
                  type: string
                assignment_description:
                  type: string
                due_date:
                  type: string
                  format: date
                score:
                  type: number
                max_score:
                  type: number
      responses:
        '201':
          description: Graded assignment created successfully
        '500':
          description: Internal server error

  /study/lectures:
    get:
      summary: Get lectures
      responses:
        '200':
          description: Lectures data
        '404':
          description: Course not found
        '500':
          description: Internal server error
    post:
      summary: Create a new lecture
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lecture_title:
                  type: string
                lecture_link:
                  type: string
                lecture_date:
                  type: string
                  format: date
                lecture_description:
                  type: string
      responses:
        '201':
          description: Lecture created successfully
        '500':
          description: Internal server error

  /genai/videochat:
    post:
      summary: Chat with the GenAI assistant about video content and explain concepts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_input:
                  type: string
                content_type:
                  type: string
                  enum: [video, concept]
                difficulty_level:
                  type: string
                  enum: [beginner, intermediate, advanced]
      responses:
        '200':
          description: Successful response from GenAI
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /genai/programming_feedback:
    post:
      summary: Get AI-generated feedback for programming tests
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                language:
                  type: string
                test_results:
                  type: object
      responses:
        '200':
          description: AI-generated feedback
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /genai/generate_study_plan:
    post:
      summary: Generate a personalized study plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                course_id:
                  type: string
                user_id:
                  type: string
                duration_weeks:
                  type: integer
      responses:
        '200':
          description: Generated study plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  study_plan:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /profile:
    get:
      summary: Get user profile
      responses:
        '200':
          description: Profile data
        '404':
          description: User not found
        '500':
          description: Internal server error

  /execute:
    post:
      summary: Execute code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
      responses:
        '200':
          description: Code execution output
        '500':
          description: Internal server error